server:
  port: 8080
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
spring:
  application:
    name: redis_demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379
    cluster:
      nodes: localhost:6379,localhost:6379,localhost:6379